### ISSUE TITLE
Improve documentation of xlsx-renderer

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/XToolset#103]
# Motivation:

The documentation (included in `packages/xlsx-renderer/README.md`) is the most important thing for package users. I want to keep the highest quality as possible.

**As https://github.com/Siemienik/XToolset/issues/104 was done first, it is able to inspire with PR: https://github.com/Siemienik/XToolset/pull/116**

## TODO:

xlsx-renderer/README.md:

* [x] update badges
* [x] add information about cli
* [x] remove section: other projects
* [x] fix typos if exists
* [x] mention about it is part of XToolset.
* [x] attempt to improve it

xlsx-renderer/package.json:

* [x] fix repo and homepage urls,
* [x] add directory props into repository
* [x] rething keywords and description, 
* [x] analyse how it might be improved.

Repo README.md:

* [x] add badges
