### ISSUE TITLE
Improve documentation of xlsx-import

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/XToolset#104]
# Motivation:

Similar like in #103 but in context of xlsx-import. The documentation (included in `packages/xlsx-import/README.md`) is the most important thing for package users. I want to keep the highest quality as possible.

## TODO:

xlsx-import/README.md:

* [x] update badges
* [x] remove redundant info about node v8&9
* [x] fix typos if exists
* [x] mention about it is part of XToolset
* [x] consider if some simplification can be performed
* [x] attempt to improve it

xlsx-import/package.json:

* [x] fix repo and homepage urls,
* [x] add directory props into repository
* [x] rethink keywords and description, 
* [x] analyse how it might be improved.

Repo README.md:

* [x] add badges
