### ISSUE TITLE
XToolSet logo

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/XToolset#105]
# Logo

I want XToolset to be perceived in the best possible light. There is still a lot of ambitious work to be done for this, and it should definitely start with the logo. Current logo is nasty, made in 5 minutes in the easiest editor ever. The purpose of this issue is to develop a new logo. 

## Actual

Currently logo is prehistorical graphic used for one part of XToolset

<details>
<summary><b>XLSX Import logo:</b></summary>

![f562e400-e091-11ea-80ff-63655008d4c7](https://user-images.githubusercontent.com/2893099/101266507-9ebc0b80-374f-11eb-9782-c8222eb0f924.png)
</details>

## Expected

In my opinion the new logo should be simple as possible, it may refer to spreadsheets topic. 

## TODO:

* [x] Upload logo here,
* [x] Upload logo into `media` folder in a fork and open new Pull request (If any problem with that I will help you on gitter). 
* [x] add logo into `README.md`
* [ ] Set new logo as a project logo in https://github.com/Siemienik/XToolset/settings

**Comment by outhomedesign-studio** [comment]
[xtoolset-logo-final.zip](https://github.com/Siemienik/XToolset/files/5824955/xtoolset-logo-final.zip)
