### ISSUE TITLE
Update GH Sponsors page

### ISSUE THREAD

**Issue by michalp4** [Siemienik/XToolset#127]
# GitHub Sponsors page

GitHub Sponsors page need to be updated because during last two months XToolSet was developed which combines xlsx-renderer and importer in one toolset. It needs also wider description and need to be pointed as a main project. Little bit more description would be good in exceljs area as well.

## Actual

Four links with little description of Pawels projects and exceljs

## Expected

- Description of what now is Pawels main area of interest (XToolSet)
- Description of the project itself with a breakdown on all components
- Few words about working on exceljs
- Maybe some info about paid support on XToolSet and exceljs

## TODO:

* [x] Some introduction would be nice
* [x] Make general description of what Pawel is working on right now
* [x] Make description of the XToolSet 
* [x] Breakdown on its components and describe them as well
* [x] Describe exceljs area of work
* [ ] Info about paid support (?)

**Comment by Siemienik** [comment]
@michalp4 I've just a little updated sponsor profile for serving more accurate information.

**Comment by michalp4** [comment]
GH Sponsor page is updated, but there is still one box to check - should we add any info about paid support? @Siemienik

**Comment by Siemienik** [comment]
I don't think so. Thank you for writing it 👍
