### ISSUE TITLE
 Graphic representations of how XToolset works

### ISSUE THREAD

**Issue by michalp4** [Siemienik/XToolset#130]
# Infographics

We need to have same good looking graphics of how XToolset works in general, of it's usage and dependencies.

Basically improved Pawels graphics, and of course, If you have any other ideas then feel free to put it here.

## Actual

Actual graphics are legible but very raw and simple

## Expected

New graphics should be also legible but they should be pimped up, more aesthetic and 
graphically enhanced

## TODO:

* [ ] Upload graphics here
* [ ] Version for social media (with logos footer bar)
* [ ] Version for documentation (without footer bar)
