### ISSUE TITLE
Improve handling the `templateFactory` argument for xlsx-renderer Render.render()

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/XToolset#136]
The `Renderer.render` function needs to pass in `templateFactory` argument, which should build from scratch Workbook model. However, it might also be fulfilled with `() => Promise.resolve(workbook)` which essentially returns one object for template and same object for output. That makes bizarre things. (What was perfectly shown here: [this request](https://github.com/Siemienik/XToolset/issues/93#issuecomment-758691081) ).

## Todo:

* [ ] Detect that instances are the same object
* [ ] Clone it by `workbook2.model = deepClone(workbook1.model)`
* [ ] Showing warning "TemplateFactory returns the same instance for each call, Value was deeply copied. Please consider about fix the templateFactory."

## Ref:

https://github.com/jacekkoziol/xlsx/pull/1/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R91-R92

          // todo @siemeinik, Add information about correct template factory
          // todo @siemienik, Add feature which detects that template and output objects are same (Consider about thrown an error or warning, or do clone if possible and works properly)

**Comment by Siemienik** [comment]
I think it isn't still important after `fromArrayBuffer` has been added (#148 #135 )
