### ISSUE TITLE
[Info] The Proposals Index

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/XToolset#144]
# Index

This index will gather and group all propositions pushed created for this project, and all packages included. 
I appreciate the existence of the index, because:

* This will reduce the number of issues. Currently, we have 7 proposal issues from all 32. That is 21% of all.
* It introduces a convenient way to search and prioritize and track the proposals.
* Other issues (which aren't proposals) will be much more manageable

## The workflow for `[Proposal]` issues:

1. Create an issue and deeply describe:
    * What is it?
    * What is the current situation?
    * What is the expected result?
    * If any, share with possible solutions.
2. Created issue will be indexed herein the appreciate group. If possible - set a priority.
3. Issue will be closed.
4. If the proposal becomes accepted, It will:
    * Reopen
    * Change into `[Draft]` or mark as `accepted`,
    * Assign into proper [project](https://github.com/Siemienik/XToolset/projects). 
    * Mark with [x] here, and moved into the bottom of the index.
5. If the proposal becomes rejected, it will be:
    * Moved into the bottom of the index.
    * Wrapped within `~`

## Proposals:

**General:**

* [ ] https://github.com/Siemienik/XToolset/issues/76 Create a workflow to automate bumping samples version up

**`xlsx-import` and `xlsx-import-cli` (`sxi`):**

* [ ] https://github.com/Siemienik/XToolset/issues/7 Horizontal list
* [ ] https://github.com/Siemienik/XToolset/issues/8 Dynamic columns
* [ ] https://github.com/Siemienik/XToolset/issues/79 Paginator
* [ ] https://github.com/Siemienik/XToolset/issues/80 Use the ExcelJs`s streaming mode
* [ ] https://github.com/Siemienik/XToolset/issues/87 Add packages into CDN

**`xlsx-import` and `xlsx-import-cli` (`sxi`):**

* [ ] https://github.com/Siemienik/XToolset/issues/99 Consider about easier xlsx-renderer usage on frontend
