### ISSUE TITLE
Common mappers implementation

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/XToolset#21]
The PR Siemienik/xlsx-import#20 refactor how the code is organised. Among others there was created new layer called `mappers` (`src/mappers`) and here I will describe how I plan to expand it.

**Remark:** 

_I marked this issue as `good first issue` because it contains list of simple and well described issues. Good practice is create one PR for one of these issues._

# Actual 

There is only file named `index.ts` with `MAPPER_DEFAULT` introduce in Siemienik/xlsx-import#19.

# Expected

This should contains handy and the most popular mappers ready to use. The first mappers how I consider to do is:

* [x] #23 upperCaseMaper: `Some Text` => `SOME TEXT`
* [x] #22 lowerCaseMaper : `Some Text` => `some text` 
* [x] #37 isEmpty - true if has no value
* [x] #39 isFilled - true if any value provided
* [x] #40 jsonMapper : `'{prop:[1,2]}'` (string) => `{prop:[1,2]}` (object with array)
* [x] #24 splitMapper: `val1,val2,val3` => `[val1,val2,val3]`
* [x] #46 numberMapper : `123` (string) => `123` (number)
* [x] #48 integerMapper: `Number.parseInt`
* [x] #53 booleanMapper: `0` => `false`
* [x] #58 dateMapper: transform date string into Date, same as `new Date`
* [x] #59 isValue - true if value match
* ~regexMapper - true if matches to regex~ **EDIT:** for further development
* ~decimalMapper: _has to define_~ **EDIT: ** for further development`

For each mapper I'm going to create new issue.

# Request for a mapper

This issue is great a place to propose mappers, so if you have any idea, write a comment.

**Comment by Siemienik** [comment]
Reviewing #45 I note that, we haven't listed here some useful mappers: 

* decimalMapper: _has to define_
* integerMapper: `Number.parseInt`
* dateMapper: transform date string into Date, same as `new Date`

I've just added it to the list above. I have to describe theirs test sets (data providers) and create issues.

**Comment by Siemienik** [comment]
As the PR https://github.com/Siemienik/XToolset/pull/192 was done, This issue is fully accomplished 🥇 Thanks to all contributors for your efforts 🍰
