### ISSUE TITLE
Add dateMapper into mappers

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/XToolset#58]
Part of #21 

# TODO:

1. [ ] Create file `src/mappers/dateMapper.ts` with function matches to type `ValueMapper<Date>`. Which parse value string into Date.
2. [ ] reexport it in `src/mappers/index.ts` 
3. [ ] Prove that it works in unit test (some present dates, some future, some past & some invalid)
4. [ ] Describe it in Readme.md

## tips:

* ExcelJS used inside xlsx-import return Date strings created by `new Date().toString()`
fi. `Thu Oct 08 2020 02:00:00 GMT+0200 (Central European Summer Time)`

For making a reservation please open draft PR with this issue linked
