### ISSUE TITLE
Add customisation for default response from jsonMapper

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/XToolset#73]
# Actual

The `jsonMapper` described in #40  and implemented in #43 has fallback mechanism that return `null` if parsing json failed.

# Expected

Default response should be customisable by calling `jsonMapper.default<TDefaultResult>(defaultResult: TDefaultResult)` which produce mapper with return type `TJsonResult | TDefaultResult`.

## Example usage:

```ts
const statusMapper = jsonMapper.default<Stats>({views: 0, unique: 0, stars: 0})

// returns default = {views: 0, unique:0, starts:0} for invalide
const stats = statusMapper<Stats>('invalid');

// returns parsed = {views: 1234, unique:10, starts:40}
const stats2 = statusMapper<Stats>('{"views": 123, "unique":10, "starts":40}');

// in a config: (column definition for vertical list)
// {key:"stats", index:5, mapper: jsonMapper.default<Stats>({views: 0, unique: 0, stars: 0})} 
```

# TODO:

1. [x] Introduce factory similar like in [splitMapper](https://github.com/Siemienik/xlsx-import/blob/41a466a/src/mappers/splitMapper.ts#L43-L55):
    * [x] define JsonMapper type
    * [x] wrap mapper into factory function
    * [x] implement setting `default`
    * [x] produce and export default `jsonMapper` created by the factory
2. [x] prove that it works by covering new changes by unit tests
3. [x] describe jsonMapper api in a Readme.md
